{
 "title": "risk-gateway <eks-prd-pci>",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance_path",
    "label": "Instance",
    "query": "live-risk-gateway,sandbox-risk-gateway"
   },
   {
    "name": "route",
    "label": "Route",
    "query": "label_values(http_request_duration_seconds_count{app=~\"$instance_path\", env=\"eks-prd-pci\"}, route)"
   },
   {
    "name": "status_code",
    "label": "Status Code",
    "query": "label_values(http_request_duration_seconds_count{app=~\"$instance_path\", env=\"eks-prd-pci\", route=~\"$route\"}, code)"
   },
   {
    "name": "southbound_target",
    "label": "Southbound Target",
    "query": "label_values(southbound_request_duration_seconds_count{app=~\"$instance_path\", env=\"eks-prd-pci\"}, target)"
   }
  ]
 },
 "panels": [
  {
   "title": "general-service-metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{app=~\"$instance_path\", env=\"eks-prd-pci\", job=\"kubernetes-pods-istio-secure\"}[1m])",
       "legendFormat": "CPU Usage {{instance}}"
      }
     ]
    },
    {
     "title": "Instance Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(up{app=~\"$instance_path\", env=\"eks-prd-pci\", job=\"kubernetes-pods-istio-secure\"})",
       "legendFormat": "Instance Count"
      }
     ]
    }
   ]
  },
  {
   "title": "node-service-metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Allocated Heap Size (bytes)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "nodejs_heap_size_total_bytes{app=~\"$instance_path\", env=\"eks-prd-pci\", job=\"kubernetes-pods-istio-secure\"}",
       "legendFormat": "Heap Size Allocated {{instance}}"
      }
     ]
    },
    {
     "title": "Heap Usage From Total Allocated (bytes)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "nodejs_heap_size_used_bytes{app=~\"$instance_path\", env=\"eks-prd-pci\", job=\"kubernetes-pods-istio-secure\"}",
       "legendFormat": "Heap Size Used {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "api-metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{app=~\"$instance_path\", env=\"eks-prd-pci\", job=\"kubernetes-pods-istio-secure\", route=~\"$route\", code=~\"$status_code\"}[1m]))",
       "legendFormat": "Request Per Second"
      }
     ]
    },
    {
     "title": "Request latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{app=~\"$instance_path\", route=~\"$route\", env=\"eks-prd-pci\", job=\"kubernetes-pods-istio-secure\", code=~\"$status_code\"}[1m])) by (le))",
       "legendFormat": "Request latency - 90th percentile"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{app=~\"$instance_path\", route=~\"$route\", env=\"eks-prd-pci\", job=\"kubernetes-pods-istio-secure\", code=~\"$status_code\"}[1m])) by (le))",
       "legendFormat": "Request latency - 95th percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{app=~\"$instance_path\", route=~\"$route\", env=\"eks-prd-pci\", job=\"kubernetes-pods-istio-secure\", code=~\"$status_code\"}[1m])) by (le))",
       "legendFormat": "Request latency - 99th percentile"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{app=~\"$instance_path\", env=\"eks-prd-pci\", job=\"kubernetes-pods-istio-secure\", code=~\"5..\", route=~\"$route\"}[1m])) / sum(rate(http_request_duration_seconds_count{app=~\"$instance_path\", env=\"eks-prd-pci\", job=\"kubernetes-pods-istio-secure\", route=~\"$route\"}[1m]))",
       "legendFormat": "Error Rate"
      }
     ]
    }
   ]
  },
  { "title": "southbound-metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Throughput (RPS)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(southbound_request_duration_seconds_count{app=~\"$instance_path\", env=\"eks-prd-pci\", job=\"kubernetes-pods-istio-secure\", target=~\"$southbound_target\", route=~\"$route\"}[1m])) by (target, route, method)",
     "legendFormat": "{{ target }} RPS"
    }
   ]
  },
  {
   "title": "Request latency by target",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(southbound_request_duration_seconds_bucket{app=~\"$instance_path\", target=~\"$southbound_target\", env=\"eks-prd-pci\", job=\"kubernetes-pods-istio-secure\"}[1d])) by (target, method, le))",
     "legendFormat": "{{ target }} {{ method }}  - 90th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(southbound_request_duration_seconds_bucket{app=~\"$instance_path\", target=~\"$southbound_target\", env=\"eks-prd-pci\", job=\"kubernetes-pods-istio-secure\"}[1d])) by (target, method, le))",
     "legendFormat": "{{ target }} {{ method }} - 95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(southbound_request_duration_seconds_bucket{app=~\"$instance_path\", target=~\"$southbound_target\", env=\"eks-prd-pci\"}[1d])) by (target, method,le))",
     "legendFormat": "{{ target }} {{ method }} - 99th percentile"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(southbound_request_duration_seconds_count{app=~\"$instance_path\", env=\"eks-prd-pci\", job=\"kubernetes-pods-istio-secure\", code=~\"5..\", route=~\"$route\", target=~\"$southbound_target\"}[1m])) / sum(rate(southbound_request_duration_seconds_count{app=~\"$instance_path\", env=\"eks-prd-pci\", job=\"kubernetes-pods-istio-secure\", route=~\"$route\", target=~\"$southbound_target\"}[1m]))",
     "legendFormat": "Error Rate"
    }
   ]
  }
 ]
}