include:
  - project: payu-clan-security/cicd/gitlab-security-template
    file: template.yaml
    ref: v2

sast_scan:
  rules:
    - when: never

detect_secrets:
  allow_failure: true

sca-test:
  extends: .sca-node_test_template
  variables:
    SNYK_ORGNAIZATION: "payu_zooz_cli"
  allow_failure: true
