apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Values.VirtualServicePrefix }}-inner-virtual-service"
  namespace: {{ .Values.Namespace }}
spec:
  hosts:
  - {{ template "service-name" . }}
  http:
  - timeout: 120s
    route:
    - destination:
        host: "{{ .Values.VirtualServicePrefix }}-service.{{ .Values.Namespace }}.svc.cluster.local"
        port:
          number: 80
