apiVersion: v1
kind: Service
metadata:
  name: {{ template "service-name" . }}
  namespace: {{ .Values.Namespace }}
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.ClientPort }}
    name: http
    protocol: TCP
  selector:
    app: {{ template "name" . }}
