#cd config/cassandra/cassandra-scripts/
#npm i
#./do-migration.sh
#cd ../../..

echo "############### ENVIRONMENT VARIABLES ###############"
echo "In what format would you like to print environment variables?"
echo "v - VsCode"
echo "w - Webstorm"
read FORMAT

if [ "$FORMAT" == "w" ]; then
  echo "############### PRINTING WEBSTORM VARIABLES ###############"
  echo "BUILD=$BUILD"
  echo "ENVIRONMENT=$ENVIRONMENT"
  echo "CLUSTER=$CLUSTER"
  echo "SERVICE_NAME=$SERVICE_NAME"
  echo "CASSANDRA_PASSWORD=$CASSANDRA_PASSWORD"
  echo "CASSANDRA_USERNAME=$CASSANDRA_USERNAME"
  echo "CASSANDRA_ADDRESSES=$CASSANDRA_ADDRESSES"
  echo "CASSANDRA_KEYSPACE=$CASSANDRA_KEYSPACE"
  echo "CASSANDRA_LOCAL_DATA_CENTER=$CASSANDRA_LOCAL_DATA_CENTER"
  echo "CASSANDRA_REPLICATION_FACTOR=$CASSANDRA_REPLICATION_FACTOR"
  echo "SERVICE_IAM_USERNAME=$SERVICE_IAM_USERNAME"
  echo "SERVICE_IAM_PASSWORD=$SERVICE_IAM_PASSWORD"
  echo "APP_NAME=$APP_NAME"
  echo "FSS_URL=$FSS_URL"
  echo "PAYMENT_STORAGE_URL=$PAYMENT_STORAGE_URL"
  echo "FRAUD_SERVICE_URL=$FRAUD_SERVICE_URL"
  echo "APPS_STORAGE_URL=$APPS_STORAGE_URL"
  echo "FEEDZAI_SERVICE_NAME=$FEEDZAI_SERVICE_NAME"
  echo "RESULT_MAPPING_URL=$RESULT_MAPPING_URL"
  echo "COUNTRIES_SERVICE_URL=$COUNTRIES_SERVICE_URL"
  echo "CURRENCIES_LOOKUP_URL=$CURRENCIES_LOOKUP_URL"
  echo "BASE_API_PAYMENTSOS_URL=$BASE_API_PAYMENTSOS_URL"
  echo "PROVIDER_CONFIGURATIONS_URL=$PROVIDER_CONFIGURATIONS_URL"
  echo "TARGET_TIMEOUT=$TARGET_TIMEOUT"
  echo "CACHE_REFRESH_INTERVAL_SECONDS=$CACHE_REFRESH_INTERVAL_SECONDS"
  echo "MAX_ACTIONS_TO_EXPAND_IN_PAYMENT=$MAX_ACTIONS_TO_EXPAND_IN_PAYMENT"
  echo "####### END VARIABLES SECTION #######"
elif [ "$FORMAT" == "v" ]; then
  echo "####### PRINTING VSCODE VARIABLES #######"
  echo "BUILD: \"$BUILD\","
  echo "ENVIRONMENT: \"$ENVIRONMENT\","
  echo "CLUSTER: \"$CLUSTER\","
  echo "SERVICE_NAME: \"$SERVICE_NAME\","
  echo "CASSANDRA_PASSWORD: \"$CASSANDRA_PASSWORD\","
  echo "CASSANDRA_USERNAME: \"$CASSANDRA_USERNAME\","
  echo "CASSANDRA_ADDRESSES: \"$CASSANDRA_ADDRESSES\","
  echo "CASSANDRA_KEYSPACE: \"$CASSANDRA_KEYSPACE\","
  echo "CASSANDRA_LOCAL_DATA_CENTER: \"$CASSANDRA_LOCAL_DATA_CENTER\","
  echo "CASSANDRA_REPLICATION_FACTOR: $CASSANDRA_REPLICATION_FACTOR,"
  echo "SERVICE_IAM_USERNAME: \"$SERVICE_IAM_USERNAME\","
  echo "SERVICE_IAM_PASSWORD: \"$SERVICE_IAM_PASSWORD\","
  echo "APP_NAME: \"$APP_NAME\","
  echo "FSS_URL: \"$FSS_URL\","
  echo "PAYMENT_STORAGE_URL: \"$PAYMENT_STORAGE_URL\","
  echo "FRAUD_SERVICE_URL: \"$FRAUD_SERVICE_URL\","
  echo "APPS_STORAGE_URL: \"$APPS_STORAGE_URL\","
  echo "FEEDZAI_SERVICE_NAME: \"$FEEDZAI_SERVICE_NAME\","
  echo "RESULT_MAPPING_URL: \"$RESULT_MAPPING_URL\","
  echo "COUNTRIES_SERVICE_URL: \"$COUNTRIES_SERVICE_URL\","
  echo "CURRENCIES_LOOKUP_URL: \"$CURRENCIES_LOOKUP_URL\","
  echo "BASE_API_PAYMENTSOS_URL: \"$BASE_API_PAYMENTSOS_URL\","
  echo "PROVIDER_CONFIGURATIONS_URL: \"$PROVIDER_CONFIGURATIONS_URL\","
  echo "TARGET_TIMEOUT: \"$TARGET_TIMEOUT\","
  echo "CACHE_REFRESH_INTERVAL_SECONDS: \"$CACHE_REFRESH_INTERVAL_SECONDS\","
  echo "MAX_ACTIONS_TO_EXPAND_IN_PAYMENT: \"$MAX_ACTIONS_TO_EXPAND_IN_PAYMENT\""
  echo "####### END VARIABLES SECTION #######"
fi

echo "Run service? (y/n)"
read RUN_SERVICE

if [ "$RUN_SERVICE" == "y" ]; then
  node ./src/server.js
fi
