#!/bin/bash

echo Setting source all centralized-config in current eks cluster
export PAYMENT_STORAGE_KEY=PAYMENT_STORAGE_${CONFIG_MAP_ENVIRONMENT}
export CASSANDRA_ADDRESSES=CASSANDRA_ADDRESS

if [[ $CLUSTER = dev ]]; then
    export PAYMENT_STORAGE_KEY=PAYMENT_STORAGE_${CONFIG_MAP_ENVIRONMENT}_QA
fi

echo "**ENVIRONMENT VARIABLES**"
echo "PAYMENT_STORAGE_KEY: $PAYMENT_STORAGE_KEY"
echo "CASSANDRA_ADDRESSES: $CASSANDRA_ADDRESSES"
