#!/bin/bash

echo Setting source all centralized-config in current eks cluster
export PAYMENT_STORAGE_KEY=PAYMENT_STORAGE_${CONFIG_MAP_ENVIRONMENT}
export APPS_STORAGE_KEY=APPLICATION_STORAGE_${CONFIG_MAP_ENVIRONMENT}_URL
export FSS_URL_KEY=FSS_URL_${CONFIG_MAP_ENVIRONMENT}
export CASSANDRA_ADDRESSES=CASSANDRA_ADDRESS

if [[ $CLUSTER = dev ]]; then
    export PAYMENT_STORAGE_KEY=PAYMENT_STORAGE_${CONFIG_MAP_ENVIRONMENT}_QA
    export APPS_STORAGE_KEY=APPLICATION_STORAGE_${CONFIG_MAP_ENVIRONMENT}_URL_QA
    export FSS_URL_KEY=FSS_URL_${CONFIG_MAP_ENVIRONMENT}_QA
fi

echo "**ENVIRONMENT VARIABLES**"
echo "PAYMENT_STORAGE_KEY: $PAYMENT_STORAGE_KEY"
echo "APPS_STORAGE_KEY: $PAYMENT_STORAGE_KEY"
echo "FSS_URL_KEY: $FSS_URL_KEY"
echo "CASSANDRA_ADDRESSES: $CASSANDRA_ADDRESSES"
