DockerImage: $APP_IMAGE
Replicas: $INSTANCES
ClientPort: 3000
Cpu: $CPUS
Memory: $MEMORY
Namespace: apps
UpdateStrategy: RollingUpdate
ImagePullSecret: regcred
ImagePullPolicy: Always
HealthCheckPath: /health
VirtualServicePrefix: $CHART_NAME
VirtualServiceMetadataName: $VIRTUAL_SERVICE_METADATA_NAME
VirtualServiceUriPrefix: $VIRTUAL_SERVICE_URI_PREFIX
VirtualServiceDestinationHost: $VIRTUAL_SERVICE_DESTINATION_HOST
SecretManager: 'enable'
EnableMetrics: 'true'
EnvironmentVariables:
  - name: LOG_LEVEL
    value: info
  - name: PORT
    value: '3000'
  - name: BUILD
    value: $BUILD
  - name: ENVIRONMENT
    value: $ENVIRONMENT
  - name: CLUSTER
    value: $CLUSTER
  - name: APP_NAME
    value: $APP_NAME
  - name: CASSANDRA_KEYSPACE
    value: $CASSANDRA_KEYSPACE
  - name: RISK_PROVIDER_SERVICE_NAME
    value: $RISK_PROVIDER_SERVICE_NAME
  - name: CASSANDRA_REPLICATION_FACTOR
    value: $CASSANDRA_REPLICATION_FACTOR
  - name: SECRETS_FILE_PATH
    value: $SECRETS_FILE_PATH
  - name: SECRET_MANAGER_PROJECT_NAMES
    value: $SECRET_MANAGER_PROJECT_NAME
  - name: FRAUD_SERVICE_URL
    value: $FRAUD_SERVICE_URL
  - name: CASSANDRA_ADDRESSES
    valueFrom:
      configMapKeyRef:
        name: centralized-config
        key: CASSANDRA_ADDRESS
  - name: FSS_URL
    valueFrom:
      configMapKeyRef:
        name: centralized-config
        key: $FSS_URL_KEY
  - name: APPS_STORAGE_URL
    valueFrom:
      configMapKeyRef:
        name: centralized-config
        key: $APPS_STORAGE_KEY
  - name: PAYMENT_STORAGE_URL
    valueFrom:
      configMapKeyRef:
        name: centralized-config
        key: $PAYMENT_STORAGE_KEY
  - name: RESULT_MAPPING_URL
    valueFrom:
      configMapKeyRef:
        name: centralized-config
        key: RESULTS_MAPPING_URL
  - name: COUNTRIES_SERVICE_URL
    valueFrom:
      configMapKeyRef:
        name: centralized-config
        key: COUNTRY_LOOKUP_URL
  - name: CURRENCIES_LOOKUP_URL
    valueFrom:
      configMapKeyRef:
        name: centralized-config
        key: CURRENCIES_LOOKUP_URL
  - name: BASE_API_PAYMENTSOS_URL
    valueFrom:
      configMapKeyRef:
        name: centralized-config
        key: BASE_API_PAYMENTSOS_URL
  - name: PROVIDER_CONFIGURATIONS_URL
    valueFrom:
      configMapKeyRef:
        name: centralized-config
        key: PCS_URL
  - name: TARGET_TIMEOUT
    value: $TARGET_TIMEOUT
  - name: CACHE_REFRESH_INTERVAL_SECONDS
    value: $CACHE_REFRESH_INTERVAL_SECONDS
  - name: MAX_ACTIONS_TO_EXPAND_IN_PAYMENT
    value: $MAX_ACTIONS_TO_EXPAND_IN_PAYMENT
  - name: MAX_ACTIONS_FOR_PAYMENT
    valueFrom:
      configMapKeyRef:
        name: centralized-config
        key: MAX_ACTIONS_FOR_PAYMENT  