# App
export SECRETS_FILE_PATH=''
export CASSANDRA_ADDRESSES=$DOCKER_IP:9042
export CASSANDRA_REPLICATION_FACTOR=1
export CASSANDRA_USERNAME=cassandra
export CASSANDRA_PASSWORD=cassandra
export CLUSTER=dev
export PAYMENT_STORAGE_URL='http://payments.com'
