DockerImage: $KONG_CONFIGURATIONS_AS_JOB_K8S_MIGRATION
Cpu: '0.1'
Memory: 128Mi
Namespace: apps
UpdateStrategy: RollingUpdate
ImagePullSecret: regcred
ImagePullPolicy: $PULL_POLICY
EnvironmentVariables:
  - name: KONG_ADMIN_URL
    value: $KONG_ADMIN_URL
  - name: CONFIGURATION
    value: $CONFIGURATION
  - name: SECRET_MANAGER_PROJECT_NAMES
    value: $KONG_CONFIG_SECRET_PROJECT
  - name: IAM_URL_INTERNAL
    value: $IAM_SERVICE_URL
